#!/bin/bash
# MOAB/Torque submission script for SciNet GPC 
#
#PBS -l nodes=1:ppn=16,walltime=10:00:00
#PBS -N RACS_ORF_run -q largemem
 
# load modules, ie. to use, eg. SamTools and BWA 
module load samtools/1.3.1 bwakit
 
# DIRECTORY TO RUN - $PBS_O_WORKDIR is directory job was submitted from
cd $PBS_O_WORKDIR
 
# EXECUTION COMMAND
# RACS repo located on $SCRATCH
# data subdirectory containing data files: INPUT and IP files
# refs subdirectory containing reference files: fasta and gff3 files
# the pipeline will attempt to use RAMDisk (/dev/shm) and autodetect maximum number of cores to use
($SCRATCH/RACS/core/countReads.sh        \
        data/SSCH1-1_Input_S2_R1_001.fastq.gz  data/SSCH1-1_ChIP_S1_R1_001.fastq.gz       \
        refs/T_thermophila_June2014_assembly.fasta  refs/T_thermophila_June2014.gff3  /dev/shm  \
        >& output.log) &

wait
